---
title: "Untitled"
output: html_document
---

```{r}
library(pacman)
p_load(tidyverse, pROC, plotROC)
select <- dplyr::select
```

```{r}
rm(list = ls())
load("rf4.RData")
load("svm_final.RData")
load("pred.lasso.RData")
load("xgb1_final.RData")
```

```{r}
roc1 <- rf4$pred[rf4$pred$mtry == rf4$bestTune$mtry, 1:4] %>%
  cbind(model = "RF", .)
roc2 <- svm_final$pred[(svm_final$pred$degree == svm_final$bestTune$degree)&
                         (svm_final$pred$scale == svm_final$bestTune$scale)&
                         (svm_final$pred$C == svm_final$bestTune$C), 1:4] %>%
  cbind(model = "SVM", .)
roc3 <- pred.lasso %>% 
  cbind(model = "LASSO", .)
roc4 <- xgb1_final$pred[(xgb1_final$pred$eta == xgb1_final$bestTune$eta)&
                          (xgb1_final$pred$max_depth == xgb1_final$bestTune$max_depth)&
                          (xgb1_final$pred$gamma == xgb1_final$bestTune$gamma)&
                          (xgb1_final$pred$colsample_bytree == xgb1_final$bestTune$colsample_bytree)&
                          (xgb1_final$pred$min_child_weight == xgb1_final$bestTune$min_child_weight)&
                          (xgb1_final$pred$subsample == xgb1_final$bestTune$subsample)&
                          (xgb1_final$pred$nrounds == xgb1_final$bestTune$nrounds), c(1, 2, 4, 5)] %>% 
  cbind(model = "XGboost", .)

roc_all <- rbind(roc1, roc2, roc3, roc4)
```

```{r, fig.height = 5, fig.width = 5.5}
plot.roc <- roc_all %>%
  ggplot(aes(m = normal, d = obs, col = factor(model, levels = c("RF", "SVM", "LASSO","XGboost")))) +
  geom_roc(n.cuts = 0, linealpha = 0.7) +
  coord_equal() +
  theme_bw() +
  #style_roc() +
  theme(axis.title.x = element_text(size = 20, face = "bold", color = "black", vjust = 0.5), 
        axis.title.y = element_text(size = 20, face = "bold", color = "black", vjust = 1.5), 
        axis.text = element_text(size = 18, face = "bold", color = "black"), 
        legend.title = element_text(size = 18, face = "bold", color = "black"), 
        legend.text = element_text(size = 16, face = "bold", color = "black"), 
        legend.position = c(0.7, 0.22),
        legend.background = element_rect(fill = "grey95", size = 0.5, linetype = "solid", color = "black")) +
  scale_color_discrete(labels = c(paste0("RF (", round(0.846, 3), ")"),
                                paste0("SVM (", round(0.834, 3), ")"),
                                paste0("LASSO (", round(0.6556, 3), ")"),
                                paste0("XGboost (", round(0.801, 3), ")"))) +
  labs(x = "False Positive Rate", y = "True Positive Rate", col = "Model (AUC)")

plot.roc

ggsave("ROC.pdf")
```








